(()=>{'use strict';
const KEY='cardboard-session-v1',$=s=>document.querySelector(s),id=()=>`id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const blankDeck=(name='Untitled deck')=>({id:id(),name,cards:[]}),blank=()=>({version:1,sessionName:'Untitled session',decks:[blankDeck()],activeDeckId:null,mode:'build'});
let state=blank();state.activeDeckId=state.decks[0].id;let available=[],drawnCards=[];
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function normalise(x){if(!x||!Array.isArray(x.decks)||!x.decks.length)return null;const decks=x.decks.map(d=>({id:d.id||id(),name:d.name||'Untitled deck',cards:Array.isArray(d.cards)?d.cards.map(c=>({id:c.id||id(),name:c.name||'Untitled card',description:c.description||'',category:c.category||'',color:c.color||'#d9d9d9',active:c.active!==false})):[]}));return{version:1,sessionName:x.sessionName||'Untitled session',decks,activeDeckId:decks.some(d=>d.id===x.activeDeckId)?x.activeDeckId:decks[0].id,mode:'build'}}
function activeDeck(){return state.decks.find(d=>d.id===state.activeDeckId)||state.decks[0]}function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='Saved locally'}function mark(){clearTimeout(mark.timer);$('#saveStatus').textContent='Saving…';mark.timer=setTimeout(save,250)}
function renderDecks(){const list=$('#deckList');list.innerHTML='';state.decks.forEach(d=>{const b=document.createElement('button');b.className='deck-item'+(d.id===state.activeDeckId?' is-active':'');b.innerHTML=`<span>${esc(d.name)}</span><small>${d.cards.length}</small>`;b.onclick=()=>{state.activeDeckId=d.id;clearForm();resetPlay();render();save()};list.append(b)});$('#deckCount').textContent=state.decks.length}
function editCard(c){$('#cardId').value=c.id;$('#cardName').value=c.name;$('#cardDescription').value=c.description;$('#cardCategory').value=c.category;$('#cardColor').value=c.color;$('#cardActive').checked=c.active;$('#builderHeading').textContent='Edit card';$('#saveCardButton').textContent='Save changes';$('#cancelEditButton').hidden=false;renderCards();$('#cardName').focus()}
function renderCards(){const d=activeDeck();$('#currentDeckName').textContent=d.name;$('#editingDeckLabel').textContent=d.name;$('#cardCount').textContent=`${d.cards.length} card${d.cards.length===1?'':'s'}`;const list=$('#cardList');list.innerHTML='';if(!d.cards.length){list.innerHTML='<div class="empty-state">No cards yet. Add the first card above.</div>';return}d.cards.forEach(c=>{const el=document.createElement('article');el.className='card-tile'+(c.active?'':' is-inactive')+(c.id===$('#cardId').value?' is-editing':'');el.style.setProperty('--card-color',c.color);el.innerHTML=`<h4>${esc(c.name)}</h4><div class="card-tile-footer"><span>${esc(c.category)||'Uncategorised'} · ${c.active?'Active':'Inactive'}</span><span class="tile-actions"><button class="mini-button icon-button" data-toggle aria-label="${c.active?'Mark inactive':'Mark active'} ${esc(c.name)}">${c.active?'◉':'○'}</button><button class="mini-button icon-button" data-delete aria-label="Delete ${esc(c.name)}">×</button></span></div>`;el.onclick=e=>{if(!e.target.closest('button'))editCard(c)};el.querySelector('[data-toggle]').onclick=e=>{e.stopPropagation();c.active=!c.active;mark();renderCards()};el.querySelector('[data-delete]').onclick=e=>{e.stopPropagation();if(confirm(`Delete “${c.name}”?`)){d.cards=d.cards.filter(x=>x.id!==c.id);mark();render()}};list.append(el)})}
function renderPlay(){const select=$('#playDeckSelect');select.innerHTML='';state.decks.forEach(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=d.name;select.append(o)});select.value=state.activeDeckId;const d=activeDeck();$('#playDeckName').textContent=d.name;$('#remainingCount').textContent=available.length;const box=$('#drawnCard');box.innerHTML='';if(!drawnCards.length)box.innerHTML='<div class="empty-card"><p class="eyebrow">READY</p><h2>Draw a card to begin.</h2><p>Your drawn cards will appear here.</p></div>';else drawnCards.forEach(card=>{const el=document.createElement('article');el.className='drawn-card';el.style.setProperty('--card-color',card.color);el.innerHTML=`<p class="eyebrow">${esc(card.category)||'CARD'}</p><h2>${esc(card.name)}</h2><p>${esc(card.description)||'No description'}</p><small>${esc(d.name)}</small>`;box.append(el)});$('#drawButton').disabled=available.length===0;$('#shuffleButton').disabled=available.length<2}
function resetPlay(){available=activeDeck().cards.filter(c=>c.active).map(c=>c.id);drawnCards=[];renderPlay()}function draw(){if(!available.length)return;const i=Math.floor(Math.random()*available.length),card=activeDeck().cards.find(c=>c.id===available[i]);available.splice(i,1);drawnCards.push(card);renderPlay()}function shuffleRemaining(){for(let i=available.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[available[i],available[j]]=[available[j],available[i]]}renderPlay()}
function render(){renderDecks();renderCards();renderPlay();document.querySelectorAll('.mode-button').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===state.mode));$('#buildMode').hidden=state.mode!=='build';$('#playMode').hidden=state.mode!=='play'}
function clearForm(){$('#cardForm').reset();$('#cardId').value='';$('#cardColor').value='#d9d9d9';$('#cardActive').checked=true;$('#builderHeading').textContent='Add a card';$('#saveCardButton').textContent='Add card';$('#cancelEditButton').hidden=true}
$('#cardForm').onsubmit=e=>{e.preventDefault();const d=activeDeck(),data={name:$('#cardName').value.trim(),description:$('#cardDescription').value.trim(),category:$('#cardCategory').value.trim(),color:$('#cardColor').value,active:$('#cardActive').checked};if(!data.name)return;const existing=d.cards.find(c=>c.id===$('#cardId').value);if(existing)Object.assign(existing,data);else d.cards.push({id:id(),...data});clearForm();mark();render()};$('#cancelEditButton').onclick=clearForm;$('#newDeckButton').onclick=()=>{const name=prompt('Name this deck','Untitled deck');if(name===null)return;const d=blankDeck(name.trim()||'Untitled deck');state.decks.push(d);state.activeDeckId=d.id;clearForm();mark();render()};$('.mode-switch').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;state.mode=b.dataset.mode;if(state.mode==='play')resetPlay();mark();render()};$('#playDeckSelect').onchange=e=>{state.activeDeckId=e.target.value;resetPlay();mark();render()};$('#drawButton').onclick=draw;$('#shuffleButton').onclick=shuffleRemaining;$('#resetPlayButton').onclick=()=>{resetPlay();mark()};
$('#sessionButton').onclick=()=>{$('#sessionName').value=state.sessionName;$('#sessionDialog').showModal()};$('#sessionName').oninput=e=>{state.sessionName=e.target.value||'Untitled session';mark()};$('#newSessionButton').onclick=()=>{if(confirm('Start a new session?')){state=blank();state.activeDeckId=state.decks[0].id;available=[];drawnCards=[];clearForm();render();save();$('#sessionDialog').close()}};$('#exportButton').onclick=()=>{save();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='cardboard-session.json';a.click()};$('#importButton').onclick=()=>{$('#importFile').value='';$('#importFile').click()};$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const n=normalise(JSON.parse(r.result));if(!n)throw Error();if(confirm('Import this session and replace the current one?')){state=n;state.activeDeckId=state.decks[0].id;clearForm();resetPlay();render();save();$('#sessionDialog').close()}}catch(err){alert('This file is not a valid Cardboard session.')}};r.readAsText(f)};$('#helpButton').onclick=()=>$('#helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());const stored=(()=>{try{return normalise(JSON.parse(localStorage.getItem(KEY)))}catch(e){return null}})();if(stored)state=stored;state.mode='build';state.activeDeckId=state.activeDeckId||state.decks[0].id;resetPlay();render();save()})();
