plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: Dr Daft's Playground
description: Playgrounds are everywhere, if you are willing to look for them.
author: Dr Haider Ali Akmal

collections:
  projects:
    output: true
    permalink: /projects/:name/

baseurl: "/playgrounds"
url: "https://haakmal.github.io"
