(function(){'use strict';
const factorData={
  Need:[['Learning','A desire to understand, practise, or develop something.'],['Connection','A desire to relate to, communicate with, or belong to others.'],['Care','A need to support, protect, maintain, or look after someone or something.'],['Navigation','A need to find a way through a place, process, or decision.'],['Expression','A need to communicate identity, feeling, opinion, or meaning.'],['Participation','A need to contribute, respond, or take part.']],
  People:[['Individual','One person acts or makes decisions alone.'],['Pair','Two people share, negotiate, or depend on the interaction.'],['Group','Several people participate in the same activity.'],['Community','The interaction connects people through a shared condition or place.'],['Novice','The person has limited experience of this kind of interaction.'],['Expert','The person brings existing knowledge and expectations.']],
  Activity:[['Finding','The person searches for, locates, or recognises something.'],['Making','The person constructs, changes, or produces something.'],['Sharing','The person gives, receives, or exchanges something with others.'],['Choosing','The person compares possibilities and commits to one.'],['Moving','The person changes position, direction, or state.'],['Coordinating','The person aligns actions, information, or timing with others.']],
  Setting:[['Private','The interaction happens in a personal or controlled space.'],['Public','The interaction is visible or available to people nearby.'],['Domestic','The interaction is part of everyday life at home or in a familiar place.'],['Institutional','The interaction is shaped by an organisation, service, or authority.'],['Temporary','The interaction occurs briefly or in a changing situation.'],['Unfamiliar','The person must act without knowing the place, system, or expectations.']],
  Form:[['Physical','The interaction relies on objects, materials, movement, or touch.'],['Digital','The interaction relies on a screen, interface, or digital response.'],['Spatial','The arrangement of a place or environment shapes the interaction.'],['Social','The interaction depends mainly on people responding to one another.'],['Service','The interaction unfolds through roles, steps, or an organised support process.'],['Hybrid','Physical, digital, spatial, and social elements work together.']]
};
const keys=Object.keys(factorData), state={current:{},history:[]}, factors=document.querySelector('#factors'), promptBox=document.querySelector('#prompt'), historyBox=document.querySelector('#history');
function factorCard(key){const card=document.createElement('article');card.className='factor-card';card.innerHTML='<div class="factor-head"><h3>'+key+'</h3></div><div class="factor-body"><select aria-label="'+key+' factor"></select><input class="custom-factor" aria-label="Custom '+key+' factor" placeholder="Enter your own term" hidden><div class="factor-actions"><span class="factor-mode">Open</span><button class="lock-button" type="button">Lock</button></div></div>';const select=card.querySelector('select'),custom=card.querySelector('.custom-factor'),lock=card.querySelector('.lock-button');factorData[key].forEach(([label,description])=>{const option=document.createElement('option');option.value=label;option.textContent=label;option.dataset.description=description;select.append(option)});const own=document.createElement('option');own.value='__custom';own.textContent='Custom term…';select.append(own);state.current[key]={value:factorData[key][0][0],description:factorData[key][0][1],locked:false,custom:false};function update(){let item=factorData[key].find(x=>x[0]===select.value);if(select.value==='__custom'){custom.hidden=false;custom.focus();state.current[key].custom=true;state.current[key].value=custom.value||'Custom term';state.current[key].description='A student-defined condition for this design.'}else{custom.hidden=true;state.current[key].custom=false;state.current[key].value=select.value;state.current[key].description=item[1]}lock.textContent=state.current[key].locked?'Locked':'Lock';lock.classList.toggle('is-locked',state.current[key].locked);card.classList.toggle('is-locked',state.current[key].locked);select.disabled=state.current[key].locked;custom.disabled=state.current[key].locked}select.onchange=()=>{card.classList.remove('is-shuffled');update()};custom.oninput=()=>{state.current[key].value=custom.value||'Custom term';state.current[key].description='A student-defined condition for this design.';mark()};lock.onclick=()=>{state.current[key].locked=!state.current[key].locked;update()};update();return card}
function renderResult(changed=[]){keys.forEach(key=>{const card=factors.querySelector('[aria-label="'+key+' factor"]').closest('.factor-card');card.classList.toggle('is-shuffled',changed.includes(key))})}
function shuffle(mode){const available=keys.filter(k=>!state.current[k].locked);if(!available.length)return;let chosen=mode==='one'?[available[Math.floor(Math.random()*available.length)]]:available;chosen.forEach(key=>{const list=factorData[key].filter(x=>x[0]!==state.current[key].value);const next=list[Math.floor(Math.random()*list.length)];state.current[key].value=next[0];state.current[key].description=next[1];state.current[key].custom=false;const select=factors.querySelector('select[aria-label="'+key+' factor"]');select.value=next[0];select.dispatchEvent(new Event('change'));});renderResult(chosen);addHistory(chosen)}
function addHistory(changed){const snapshot={id:Date.now(),changed,values:Object.fromEntries(keys.map(k=>[k,state.current[k].value]))};state.history.unshift(snapshot);renderHistory()}
function renderHistory(){if(!state.history.length){historyBox.innerHTML='<p class="empty">No shuffles saved yet.</p>';return}historyBox.innerHTML='';state.history.forEach((entry,index)=>{const el=document.createElement('div');el.className='history-entry';el.innerHTML='<strong>Shuffle '+String(state.history.length-index).padStart(2,'0')+'</strong><div><p>'+keys.map(k=>entry.values[k]).join(' · ')+'</p><small>Changed: '+entry.changed.join(', ')+'</small></div><div class="history-actions"><button type="button" data-restore="'+entry.id+'">Restore</button><button type="button" data-remove="'+entry.id+'">Remove</button></div>';historyBox.append(el)});historyBox.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const e=state.history.find(x=>x.id==b.dataset.restore);keys.forEach(k=>{state.current[k].value=e.values[k];const s=factors.querySelector('select[aria-label="'+k+' factor"]');s.value=e.values[k]});renderResult(e.changed)});historyBox.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.history=state.history.filter(x=>x.id!=b.dataset.remove);renderHistory()})}
keys.forEach(k=>factors.append(factorCard(k)));document.querySelector('#shuffleAll').onclick=()=>shuffle('all');document.querySelector('#shuffleUnlocked').onclick=()=>shuffle('all');document.querySelector('#changeOne').onclick=()=>shuffle('one');document.querySelector('#reset').onclick=()=>{keys.forEach(k=>{state.current[k].value=factorData[k][0][0];const s=factors.querySelector('select[aria-label="'+k+' factor"]');s.value=state.current[k].value});renderResult([])};document.querySelector('#helpButton').onclick=()=>document.querySelector('#helpDialog').showModal();document.querySelector('#closeHelp').onclick=()=>document.querySelector('#helpDialog').close();renderResult([]);
})();
