/*
  SEER'S TABLE — INTERFACE COPY
  Keep thematic and classroom terminology together so the language layer can
  be refined without touching application logic.
*/
window.SEERS_TABLE_COPY = {
  seer: {
    toolsTitle: "The Seer’s Table",
    menuAria: "Open tools",
    bookLabel: "Grimoire",
    bookAria: "Open grimoire",
    rename: "Rename grimoire",
    sessions: "My grimoires",
    export: "Export spell book",
    import: "Import spell book",
    print: "Print / Save PDF",
    help: "How this works",
    quandary: "Quandary",
    editQuandary: "Edit quandary",
    set: "set",
    ingredients: "Ingredients",
    editIngredients: "Edit ingredients",
    spells: "Spells",
    returnTable: "Return to the Seer’s table",
    seerTable: "The Seer’s table",
    craft: "Craft the enchantment.",
    cards: "Cards",
    crystal: "Crystal ball",
    yourSpell: "Your spell",
    desireCard: "Desire",
    powerCard: "Power",
    draw: "Draw",
    read: "Read",
    craftStep: "Craft",
    theCards: "the cards",
    theCrystal: "the crystal",
    theSpell: "the spell",
    ether: "The Ether",
    disturb: "Pull from the Ether",
    editSpell: "Edit this spell",
    saveSpell: "Save changes",
    craftAnother: "Craft another spell",
    studioMode: "Studio",
    seerMode: "Seer’s Table",
    modeHint: "Experience mode",
    lockedTitle: "The Grimoire is already enchanted",
    lockedBody: [
      "Your spells have already been crafted from this quandary. Changing the starting point now would change the meaning of what you have explored.",
      "For a new direction, begin a new Grimoire. Your current Grimoire will remain safely in your collection."
    ],
    newSession: "New Grimoire",
    sessionList: "My grimoires",
    deleteSession: "Delete this spell book?",
    keepLocked: "Keep this quandary",
    newLocked: "Start a new Grimoire",
    ingredientsLocked: "The ingredients are set for this Grimoire. Begin a new Grimoire to change them."
  },
  studio: {
    toolsTitle: "Interaction Ideation",
    menuAria: "Open tools",
    bookLabel: "Ideation record",
    bookAria: "Open ideation record",
    rename: "Rename session",
    sessions: "My sessions",
    export: "Export ideation record",
    import: "Import ideation record",
    print: "Print / Save PDF",
    help: "How this works",
    quandary: "Interaction problem",
    editQuandary: "Edit interaction",
    set: "set",
    ingredients: "Contextual factors",
    editIngredients: "Edit contextual factors",
    spells: "Concepts",
    returnTable: "Return to ideation workspace",
    seerTable: "Ideation workspace",
    craft: "Develop the interaction.",
    cards: "Provocations",
    crystal: "Contextual lens",
    yourSpell: "Your concept",
    desireCard: "Human desire",
    powerCard: "Interaction capability",
    draw: "Generate",
    read: "Consider",
    craftStep: "Describe",
    theCards: "the provocations",
    theCrystal: "the context",
    theSpell: "the concept",
    ether: "Provocation",
    disturb: "Apply a What If?",
    editSpell: "Edit this concept",
    saveSpell: "Save changes",
    craftAnother: "Develop another concept",
    studioMode: "Studio",
    seerMode: "Seer’s Table",
    modeHint: "Experience mode",
    lockedTitle: "This interaction problem is already in use",
    lockedBody: [
      "You have already developed concepts from this starting point. Changing it now would make the existing ideation record inconsistent.",
      "For a different direction, begin a new session. Your current ideation record will remain safely in your collection."
    ],
    newSession: "New session",
    sessionList: "My sessions",
    print: "Print / Save PDF",
    deleteSession: "Delete this ideation record?",
    keepLocked: "Keep this interaction problem",
    newLocked: "Start a new session",
    ingredientsLocked: "The contextual factors are set for this session. Begin a new session to change them."
  }
};
