window.PRINCIPLES_EXAMPLES={
  "./example-simple.json":{activeId:"digital-main",maps:[{id:"digital-main",name:"Library catalogue · full search",context:"A student searches the university library website, narrows the results, opens a book record, and saves the call number.",type:"Digital",notes:"All rows are observations. Change notes show where the student could continue investigating without turning the map into a conceptualised solution.",rows:[
    {location:"Opening page",principle:"Visibility",description:"The student can see the catalogue name and a search field, but the available search types are not immediately visible.",change:"Observe whether first-time users know what can be searched."},
    {location:"Search field",principle:"Affordance",description:"The large rectangular field and placeholder text suggest that the student can type a title or author.",change:"",signifiers:["Placeholder text","Search icon"]},
    {location:"Search submission",principle:"Mapping",description:"The student presses Enter and expects the results to update. The relationship between typing and searching is understandable.",change:"",signifiers:["Keyboard submission","Search button"]},
    {location:"Loading results",principle:"Feedback",description:"The page briefly changes before the results appear. The student waits without repeating the search.",change:"Observe whether a clearer loading response would reduce uncertainty."},
    {location:"Results heading",principle:"Visibility",description:"The current search term and result count are visible above the list, helping the student confirm that the search worked.",change:"",signifiers:["Search term","Result count"]},
    {location:"Filter panel",principle:"Constraints",description:"The filters limit the result set, but the student pauses before choosing between format, date, and subject.",change:"Test whether a recommended first filter would help."},
    {location:"Book result card",principle:"Consistency",description:"Each result presents a title, author, format, and action in the same order, allowing the student to scan several results.",change:"Observe whether repeated card structure supports comparison."},
    {location:"Book record",principle:"Visibility",description:"The call number and availability are shown near the top of the record, while related information sits further down the page.",change:"Observe what information the student looks for first."}
  ]},{id:"digital-detail",name:"Library catalogue · saving a book",context:"A closer map of the later steps: opening a result, checking availability, and saving the call number for later.",type:"Digital",notes:"This map isolates a smaller portion of the same longer interaction.",rows:[
    {location:"Book record header",principle:"Visibility",description:"The title and author are prominent, so the student can confirm that the selected record is the intended book.",change:""},
    {location:"Availability panel",principle:"Feedback",description:"The availability status changes when the student selects a library location.",change:"Observe whether the update is noticeable and understandable."},
    {location:"Location selector",principle:"Mapping",description:"The student expects the selected library location to control the availability information shown below it.",change:""},
    {location:"Save or email action",principle:"Affordance",description:"The action appears possible because it is presented as a labelled button near the call number.",change:"",signifiers:["Button border","Action label"]},
    {location:"Saved confirmation",principle:"Feedback",description:"A short confirmation appears after the student saves the record, but it disappears before the student reads all of it.",change:"Test a persistent confirmation state."}
  ]}]},
  "./example-physical.json":{activeId:"physical-main",maps:[{id:"physical-main",name:"Community noticeboard · finding an event",context:"A resident approaches a physical noticeboard, scans several notices, finds a local event, and decides whether to take the information with them.",type:"Physical",notes:"All rows are observations. Change notes record possible follow-up questions rather than proposed solutions.",rows:[
    {location:"Approaching the board",principle:"Affordance",description:"The framed board, visible papers, and open surface suggest that people can stop, read, and add notices.",change:"",signifiers:["Open board surface","Visible papers","Heading: Community notices"]},
    {location:"Board categories",principle:"Visibility",description:"Coloured headings separate events, services, and local groups, although the colour meaning is not immediately obvious.",change:"Observe whether people use the headings or scan every notice."},
    {location:"Scanning notices",principle:"Consistency",description:"Notice sizes and title positions vary, so the resident changes reading distance and direction several times.",change:"Observe which repeated structure would make scanning easier."},
    {location:"Selecting a notice",principle:"Mapping",description:"The resident removes a notice from the board and holds it closer to read the smaller details.",change:"",signifiers:["Pinned corners","Large title","Small detail text"]},
    {location:"Taking information away",principle:"Constraints",description:"The resident can photograph the notice, but there is no obvious tear-off tab or writing surface nearby.",change:"Observe what people do when they want to keep the information."},
    {location:"Returning to the board",principle:"Feedback",description:"After replacing a notice, the resident has no clear indication that it is secure and aligned with the other notices.",change:"Observe whether the physical arrangement communicates completion."}
  ]},{id:"physical-detail",name:"Community noticeboard · posting a notice",context:"A closer map of the later steps: preparing a notice, finding a space, pinning it, and returning to check it.",type:"Physical",notes:"This map isolates the posting activity as a second view of the same physical system.",rows:[
    {location:"Writing area",principle:"Affordance",description:"A small tray of blank paper and pens suggests that visitors can create a new notice.",change:"",signifiers:["Blank paper","Pens","Tray label"]},
    {location:"Notice template",principle:"Constraints",description:"The paper provides spaces for a title, date, location, and contact details, limiting how much information can be added.",change:"Observe whether the fields support short, readable notices."},
    {location:"Pin tray",principle:"Visibility",description:"Pins are visible beside the writing area, but the visitor initially looks around the board before finding them.",change:"Observe the relationship between the writing area and pin tray."},
    {location:"Finding an empty space",principle:"Mapping",description:"The visitor looks for a gap that matches the category of the notice and places it below similar notices.",change:""},
    {location:"Posted notice",principle:"Feedback",description:"The completed notice is visible on the board, but the visitor cannot tell whether it will remain until the event date.",change:"Observe whether review dates or maintenance cues are understood."}
  ]}]},
  "./example-hybrid.json":{activeId:"hybrid-main",maps:[{id:"hybrid-main",name:"Museum guide · entering and orienting",context:"A visitor enters an exhibition, collects a handheld guide, reads the room signage, and chooses where to begin.",type:"Hybrid",notes:"All rows are observations across physical, digital, spatial, and social parts of one interaction.",rows:[
    {location:"Guide collection point",principle:"Affordance",description:"The device tray, screen, and printed instruction suggest that the visitor can pick up a guide and begin.",change:"",signifiers:["Device tray","Screen frame","Printed instruction"]},
    {location:"Handheld guide",principle:"Mapping",description:"The visitor turns the device toward the exhibition and expects the screen to relate to the room in front of them.",change:"",signifiers:["Camera opening","Room image","Device orientation"]},
    {location:"Room entrance",principle:"Visibility",description:"The room number is large on the wall and is also shown on the projected map, allowing the visitor to confirm their location.",change:"",signifiers:["Large room number","Projected map","Directional arrow"]},
    {location:"Choosing where to begin",principle:"Constraints",description:"The guide offers several highlighted works, but the visitor pauses because it is unclear whether they should follow the suggested route or choose freely.",change:"Observe how visitors interpret the difference between recommendation and requirement."},
    {location:"First artwork",principle:"Feedback",description:"When the visitor points the device at the artwork, a vibration and screen transition indicate that it has been recognised.",change:"",signifiers:["Haptic pulse","Screen transition","Recognition tone"]},
    {location:"Physical and digital labels",principle:"Consistency",description:"The visitor compares the room language on the device with the wall labels. Matching names help them move between the two systems.",change:"Observe which terms visitors repeat when asking staff for help."}
  ]},{id:"hybrid-detail",name:"Museum guide · following an artwork route",context:"A closer map of the later steps: recognising an artwork, following a suggested route, and returning the guide.",type:"Hybrid",notes:"This map isolates a longer sequence where physical and digital responses must remain connected.",rows:[
    {location:"Artwork recognition",principle:"Feedback",description:"The device vibrates and displays the artwork title after the visitor holds it steady for a moment.",change:"Observe whether the response arrives at the right time."},
    {location:"Artwork information",principle:"Visibility",description:"The title is immediately visible, while the longer description requires a separate action to reveal.",change:"Observe what information visitors expect to see first."},
    {location:"Suggested route",principle:"Mapping",description:"The visitor follows an arrow on the device and then looks for the same direction in the physical room.",change:"Observe whether the digital arrow and physical signage agree."},
    {location:"Asking staff for help",principle:"Affordance",description:"A staff member is visible in the room, but the guide does not clearly indicate when or how the visitor can ask for assistance.",change:"",signifiers:["Visible staff desk","Help icon","Staff badge"]},
    {location:"Returning the guide",principle:"Constraints",description:"The visitor places the device in the tray, but the tray accepts it in several orientations and gives no clear completion response.",change:"Observe whether the return action can be completed confidently."}
  ]}]}
};
